### ISSUE TITLE
lets add a dark mode and light mode switch

### ISSUE THREAD

**Issue by Astronoma-REAL** [Astronoma-REAL/Astronoma#2]
it would require a database which jbuster has already made for andromeda-2b
in the database we would keep the prefernces of the user and whenever the website loads itwill fetch the cache from the user and show it to the data base and then determine what mode was last there, and till it feches it will display a loading sceen

**Comment by Astronoma-REAL** [comment]
@JBusterJ @tejulion1234 look into it

**Comment by ProScienceDude** [comment]
There is one issue

We can change only one page color with 1 switch
